//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnificacionDocumentoDao.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.50.66;Initial Catalog=BD_ConvocatoriaSenado_ConsejeroJF;User " +
            "ID=sa")]
        public string BD_ConvocatoriaSenado_ConsejeroJFConnectionString {
            get {
                return ((string)(this["BD_ConvocatoriaSenado_ConsejeroJFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.50.66;Initial Catalog=BD_ConvocatoriaSenado_TitularCNDH;User " +
            "ID=sa;Password=5en4d0.Pr0d")]
        public string BD_ConvocatoriaSenado_TitularCNDHConnectionString {
            get {
                return ((string)(this["BD_ConvocatoriaSenado_TitularCNDHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.64;Initial Catalog=BD_ConfiguracionDocumentoPDF;User ID=sa" +
            ";Password=5en4d0.C0m")]
        public string BD_ConfiguracionDocumentoPDFConnectionString {
            get {
                return ((string)(this["BD_ConfiguracionDocumentoPDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.50.66;Initial Catalog=BD_ConfiguracionDocumentoPDF;Persist Se" +
            "curity Info=True;User ID=sa;Password=5en4d0.Pr0d")]
        public string BD_ConfiguracionDocumentoPDFConnectionString1 {
            get {
                return ((string)(this["BD_ConfiguracionDocumentoPDFConnectionString1"]));
            }
        }
    }
}
