#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnificacionDocumentoDao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_ConfiguracionDocumentoPDF")]
	public partial class BaseDatosDocumentsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public BaseDatosDocumentsDataContext() : 
				base(global::UnificacionDocumentoDao.Properties.Settings.Default.BD_ConfiguracionDocumentoPDFConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDocumentsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDocumentsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDocumentsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDocumentsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdjuntarDocumentosConvocatoria")]
		public ISingleResult<AdjuntarDocumentosConvocatoriaResult> AdjuntarDocumentosConvocatoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipoConvocatoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoConvocatoria);
			return ((ISingleResult<AdjuntarDocumentosConvocatoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ConsultarDocumentosPorUnificar")]
		public ISingleResult<ConsultarDocumentosPorUnificarResult> ConsultarDocumentosPorUnificar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipoConvocatoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuarioAspirante, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bDocumentoPublico)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoConvocatoria, idUsuarioAspirante, bDocumentoPublico);
			return ((ISingleResult<ConsultarDocumentosPorUnificarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ConsultarRutaDocumentos")]
		public ISingleResult<ConsultarRutaDocumentosResult> ConsultarRutaDocumentos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipoConvocatoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoConvocatoria);
			return ((ISingleResult<ConsultarRutaDocumentosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DocumentosPorUnificar")]
		public ISingleResult<DocumentosPorUnificarResult> DocumentosPorUnificar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTipoConvocatoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoConvocatoria);
			return ((ISingleResult<DocumentosPorUnificarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GuardarDetalleDocumentoFinal")]
		public ISingleResult<GuardarDetalleDocumentoFinalResult> GuardarDetalleDocumentoFinal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(6)")] string vTipoAccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idAspiranteDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idConvocatoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(160)")] string vNombreDocumentoFinal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuarioAlta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bDocumentoCompleto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bDocumentoPublico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string vObservaciones, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuarioValidacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bDocumentoGeneradoCompleto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string vMensajeError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary vrArchivoFinal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDocumentoAdjuntarActualizar)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vTipoAccion, idAspiranteDocumento, idConvocatoria, vNombreDocumentoFinal, idUsuarioAlta, bDocumentoCompleto, bDocumentoPublico, vObservaciones, idUsuarioValidacion, bDocumentoGeneradoCompleto, vMensajeError, vrArchivoFinal, idDocumentoAdjuntarActualizar);
			return ((ISingleResult<GuardarDetalleDocumentoFinalResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_insertaValoresLog")]
		public int sp_insertaValoresLog([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string ruta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string vTipoError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(700)")] string vDescripcionError, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string vparametros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, ruta, vTipoError, vDescripcionError, vparametros);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ConsultarConvocatoriasActivas")]
		public ISingleResult<ConsultarConvocatoriasActivasResult> ConsultarConvocatoriasActivas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ConsultarConvocatoriasActivasResult>)(result.ReturnValue));
		}
	}
	
	public partial class AdjuntarDocumentosConvocatoriaResult
	{
		
		private System.Nullable<bool> _bAdjuntarDocumentoSeccion;
		
		public AdjuntarDocumentosConvocatoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bAdjuntarDocumentoSeccion", DbType="Bit")]
		public System.Nullable<bool> bAdjuntarDocumentoSeccion
		{
			get
			{
				return this._bAdjuntarDocumentoSeccion;
			}
			set
			{
				if ((this._bAdjuntarDocumentoSeccion != value))
				{
					this._bAdjuntarDocumentoSeccion = value;
				}
			}
		}
	}
	
	public partial class ConsultarDocumentosPorUnificarResult
	{
		
		private int _idUsuarioAspirante;
		
		private string _vNombreDoc;
		
		private System.Nullable<bool> _vDocumentoPublico;
		
		private string _vNombreTipoDocumento;
		
		private string _vRutaTipoDocumento;
		
		public ConsultarDocumentosPorUnificarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioAspirante", DbType="Int NOT NULL")]
		public int idUsuarioAspirante
		{
			get
			{
				return this._idUsuarioAspirante;
			}
			set
			{
				if ((this._idUsuarioAspirante != value))
				{
					this._idUsuarioAspirante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vNombreDoc", DbType="VarChar(231)")]
		public string vNombreDoc
		{
			get
			{
				return this._vNombreDoc;
			}
			set
			{
				if ((this._vNombreDoc != value))
				{
					this._vNombreDoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vDocumentoPublico", DbType="Bit")]
		public System.Nullable<bool> vDocumentoPublico
		{
			get
			{
				return this._vDocumentoPublico;
			}
			set
			{
				if ((this._vDocumentoPublico != value))
				{
					this._vDocumentoPublico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vNombreTipoDocumento", DbType="VarChar(500)")]
		public string vNombreTipoDocumento
		{
			get
			{
				return this._vNombreTipoDocumento;
			}
			set
			{
				if ((this._vNombreTipoDocumento != value))
				{
					this._vNombreTipoDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vRutaTipoDocumento", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string vRutaTipoDocumento
		{
			get
			{
				return this._vRutaTipoDocumento;
			}
			set
			{
				if ((this._vRutaTipoDocumento != value))
				{
					this._vRutaTipoDocumento = value;
				}
			}
		}
	}
	
	public partial class ConsultarRutaDocumentosResult
	{
		
		private int _idConvocatoria;
		
		private int _idAspiranteDocumento;
		
		private string _vNombreRutaCarpeta;
		
		private bool _bDocumentosPublicos;
		
		public ConsultarRutaDocumentosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idConvocatoria", DbType="Int NOT NULL")]
		public int idConvocatoria
		{
			get
			{
				return this._idConvocatoria;
			}
			set
			{
				if ((this._idConvocatoria != value))
				{
					this._idConvocatoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAspiranteDocumento", DbType="Int NOT NULL")]
		public int idAspiranteDocumento
		{
			get
			{
				return this._idAspiranteDocumento;
			}
			set
			{
				if ((this._idAspiranteDocumento != value))
				{
					this._idAspiranteDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vNombreRutaCarpeta", DbType="VarChar(160)")]
		public string vNombreRutaCarpeta
		{
			get
			{
				return this._vNombreRutaCarpeta;
			}
			set
			{
				if ((this._vNombreRutaCarpeta != value))
				{
					this._vNombreRutaCarpeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bDocumentosPublicos", DbType="Bit NOT NULL")]
		public bool bDocumentosPublicos
		{
			get
			{
				return this._bDocumentosPublicos;
			}
			set
			{
				if ((this._bDocumentosPublicos != value))
				{
					this._bDocumentosPublicos = value;
				}
			}
		}
	}
	
	public partial class DocumentosPorUnificarResult
	{
		
		private int _REG;
		
		public DocumentosPorUnificarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REG", DbType="Int NOT NULL")]
		public int REG
		{
			get
			{
				return this._REG;
			}
			set
			{
				if ((this._REG != value))
				{
					this._REG = value;
				}
			}
		}
	}
	
	public partial class GuardarDetalleDocumentoFinalResult
	{
		
		private int _idErrorReturn;
		
		private string _vDescripcionErrorReturn;
		
		public GuardarDetalleDocumentoFinalResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idErrorReturn", DbType="Int NOT NULL")]
		public int idErrorReturn
		{
			get
			{
				return this._idErrorReturn;
			}
			set
			{
				if ((this._idErrorReturn != value))
				{
					this._idErrorReturn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vDescripcionErrorReturn", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string vDescripcionErrorReturn
		{
			get
			{
				return this._vDescripcionErrorReturn;
			}
			set
			{
				if ((this._vDescripcionErrorReturn != value))
				{
					this._vDescripcionErrorReturn = value;
				}
			}
		}
	}
	
	public partial class ConsultarConvocatoriasActivasResult
	{
		
		private int _idConvocatoria;
		
		private string _vNombreServidor;
		
		private string _vIpServidor;
		
		private string _vNombreBaseDatos;
		
		private string _vUsuario;
		
		private string _vContraseña;
		
		private System.Nullable<bool> _bActivo;
		
		public ConsultarConvocatoriasActivasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idConvocatoria", DbType="Int NOT NULL")]
		public int idConvocatoria
		{
			get
			{
				return this._idConvocatoria;
			}
			set
			{
				if ((this._idConvocatoria != value))
				{
					this._idConvocatoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vNombreServidor", DbType="VarChar(19)")]
		public string vNombreServidor
		{
			get
			{
				return this._vNombreServidor;
			}
			set
			{
				if ((this._vNombreServidor != value))
				{
					this._vNombreServidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vIpServidor", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string vIpServidor
		{
			get
			{
				return this._vIpServidor;
			}
			set
			{
				if ((this._vIpServidor != value))
				{
					this._vIpServidor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vNombreBaseDatos", DbType="VarChar(190) NOT NULL", CanBeNull=false)]
		public string vNombreBaseDatos
		{
			get
			{
				return this._vNombreBaseDatos;
			}
			set
			{
				if ((this._vNombreBaseDatos != value))
				{
					this._vNombreBaseDatos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vUsuario", DbType="VarChar(29)")]
		public string vUsuario
		{
			get
			{
				return this._vUsuario;
			}
			set
			{
				if ((this._vUsuario != value))
				{
					this._vUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vContraseña", DbType="VarChar(29)")]
		public string vContraseña
		{
			get
			{
				return this._vContraseña;
			}
			set
			{
				if ((this._vContraseña != value))
				{
					this._vContraseña = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bActivo", DbType="Bit")]
		public System.Nullable<bool> bActivo
		{
			get
			{
				return this._bActivo;
			}
			set
			{
				if ((this._bActivo != value))
				{
					this._bActivo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
